# Generated by Django 4.1.2 on 2022-10-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Name')),
                ('product_price', models.CharField(max_length=200, verbose_name='Price')),
                ('product_category', models.CharField(max_length=200, verbose_name='Category')),
            ],
        ),
    ]
