# Generated by Django 4.1.2 on 2022-10-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_discount',
            field=models.IntegerField(default=0, verbose_name='Discount'),
        ),
    ]
