# Generated by Django 4.1.2 on 2022-12-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_formforemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='formforemail',
            name='user_file',
            field=models.FileField(default='./static/img/product_img.png', upload_to='product'),
        ),
    ]
